#!/bin/sh
#This is a sample preinstall or postinstall script.
#Your logic goes here.
#sudo open -a "Terminal" --new $PACKAGE_PATH/Contents/Resources/cyonagent_mac "-controller" "https://asm-dev.proxyon.cloud"
exit 0